In [1]:
import numpy as np

In [2]:
# Say a(activation) is the output of the neural network at the last layer
a = np.random.randn(5)  # 5 unite
a

array([-0.35584326,  0.36469856,  0.84767097, -0.18718154, -2.62909901])

In [3]:
# These five different numbers represent 5 different activations at 5 different nodes

In [4]:
expa = np.exp(a)
expa

array([ 0.70058242,  1.44007984,  2.33420409,  0.82929318,  0.07214343])

In [5]:
answer = expa / expa.sum()

In [6]:
answer

array([ 0.13030933,  0.2678569 ,  0.43416528,  0.15424971,  0.01341878])

In [7]:
# They are probabilities so will get added to 1
answer.sum()

1.0

In [8]:
# Let's do this my matrix

In [9]:
A = np.random.randn(100, 5) # this is 100 samples and 5 classes

In [10]:
expA = np.exp(A)

In [15]:
answer = expA / expA.sum(axis = 1, keepdims=True)  # sum along the rows

In [17]:
answer.sum(axis = 1)  # sum along rows = 1

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])