In [1]:
import numpy as np

In [12]:
# Create data to perform the tasks
N = 100 # 100 observations
D = 2 # two dimensions x1 and x2

X = np.random.randn(N, D) # Standard Normal distribution of dimension N x D
ones = np.array([[1]*N]).T  # first we create an array of [1] N elements then transpose it yo have N rows
Xb = np.concatenate((ones, X), axis = 1)  # adding the bias term
Xb[0:3]

array([[ 1.        ,  1.50195283, -0.08116284],
       [ 1.        , -0.22844249,  0.19730432],
       [ 1.        ,  0.06844851, -0.7882128 ]])

In [23]:
# Let's randomly initialize the weights vector-
w = np.random.randn(D + 1) # for D dimenions and the 1 bias term
w

array([-0.08140637, -1.67120485, -0.24134048])

In [14]:
# First let's calculate the Inner product between each row of X and w
z = Xb.dot(w)
# Now, here's a strange thing. We usually write wTX (w transpose X) as the inner product because w and D are usually D x 1 column
# vector. In this case, we have N x D where each X is a 1 x D row vector and w is 1 x D . So, the inner product should give us
# N x 1 vector

In [16]:
z.shape

(100,)

In [33]:
z[0:10]  # 100 scalar values which come from the dot product i.e. (w.T)X

array([-1.50784616,  1.76748722,  0.59565622, -0.95368689,  1.24232059,
       -0.08549886, -0.12956088,  1.30154866,  4.19983487, -4.21141614])

In [24]:
#z1_t = Xb.dot(w.T)
#z1_t.shape
# (100, )  # note in both we get N x 1 column vector.

In [25]:
# Now apply the sigmoid to get the value of the function-
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [30]:
result = sigmoid(z)
print(len(result))  # so, it's got 100 different values for the function 

100


In [31]:
result # they all lie between 0 and 1

array([ 0.18125821,  0.8541449 ,  0.64466189,  0.27814396,  0.77596769,
        0.4786383 ,  0.46765501,  0.7860955 ,  0.98522356,  0.01460878,
        0.95996566,  0.33065887,  0.04152121,  0.97309926,  0.74340336,
        0.78331144,  0.19926458,  0.7000234 ,  0.91516557,  0.93350152,
        0.81178467,  0.49478358,  0.98630427,  0.71093563,  0.56071351,
        0.81257747,  0.19283069,  0.96098846,  0.97326245,  0.9595683 ,
        0.94577124,  0.45245458,  0.12967341,  0.93206098,  0.30961014,
        0.93829592,  0.41636794,  0.91480634,  0.51454723,  0.52831042,
        0.67307099,  0.9865215 ,  0.87512751,  0.43692462,  0.71711333,
        0.68908508,  0.77923678,  0.60512266,  0.23479699,  0.31907087,
        0.44673977,  0.63874591,  0.96239789,  0.29201664,  0.90498289,
        0.89643155,  0.18285079,  0.71743157,  0.7212297 ,  0.84059356,
        0.79948832,  0.91226759,  0.76699564,  0.6639063 ,  0.20930495,
        0.83897394,  0.57069154,  0.58680993,  0.63461622,  0.98